### ISSUE TITLE
Assertion incorrect usage resulting in abrupt termination of program instance

### ISSUE THREAD

**Issue by Zhi-You** [AY2021S1-CS2113T-F12-3/tp#128]
This bug happened for a user input of 'quiz t/yay n/342'.
Can consider removing the assertions completely because in QuizQuestionsManager it actually has an exception that checks for such inputs, can try it in the app and see what is being displayed to the user.

![image](https://user-images.githubusercontent.com/49060098/96820018-989bf500-1457-11eb-9aee-fa70532b3f1d.png)

![image](https://user-images.githubusercontent.com/49060098/96820025-9cc81280-1457-11eb-9668-a1b19c0605e3.png)

![image](https://user-images.githubusercontent.com/49060098/96820033-a05b9980-1457-11eb-90d0-41a5d516bedb.png)

**Comment by kstonekuan** [comment]
I think you should move the exceptions higher up so it doesn't reach this assertion
